### ISSUE TITLE
wireguard slower than openvpn

### ISSUE THREAD

**Issue by zx900930** [goofball222/pritunl#15]
## Reporting bugs/issues

* When reporting a bug/issue:
    * Ensure that you are using the latest release.
    * Revert any custom modifications or environment varibles to insure they're not the cause.

* Please provide the following information:
    * OS/distribution version (command for your OS may differ):
    ```bash
    user@host:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 20.04.4 LTS
    Release:        20.04
    Codename:       focal
    ```

    * Docker version:
    ```bash
    user@host:~$ docker --version
    Docker version 20.10.16, build aa7e414
    ```

    * Labels from container:
    ```bash
    user@host:~$ docker inspect goofball222/pritunl:latest
    ...
                "Labels": {
                "org.opencontainers.image.created": "2022-05-15T18:57:46.301Z",
                "org.opencontainers.image.description": "Pritunl Server",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "47f88b94c4eaa49f58e7bab3bce8092452660184",
                "org.opencontainers.image.source": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.title": "Pritunl Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.30.3157.70"
            }
    ...
    ```

    * Details on how to reproduce the trouble, if available:
    Setting up a pritunl server on docker desktop 4.9 using WSL2 backend, host system is Windows Server 2022
   Docker Compose:
```
version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - ./db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    depends_on:
        - mongo
    network_mode: bridge
    privileged: true
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2080:80
      - 2443:443
      - 1194:1194
      - 1195:1195/udp
    environment:
      - TZ=Europe/Paris
      - REVERSE_PROXY=true
      - WIREGUARD=true
```
reverse proxyed by nginx proxy manager

Both the Openvpn and Wireguard connection are OK.

The only problem is the Openvpn was 2 times faster than Wireguard, so there might be some performance issues for wireguard.

Both are using the same pritunal profile on official pritunal windows client, and tested multiple times.
Other services in the network are completely shut down during the test to ensure it's not caused by 3rd party services. 

Openvpn:
```
iperf3 -c 192.168.0.3                                      
Connecting to host 192.168.0.3, port 5201
[  4] local 192.168.232.3 port 6582 connected to 192.168.0.3 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  9.88 MBytes  82.6 Mbits/sec
[  4]   1.00-2.00   sec  9.75 MBytes  81.9 Mbits/sec
[  4]   2.00-3.00   sec  12.4 MBytes   104 Mbits/sec
[  4]   3.00-4.00   sec  13.1 MBytes   110 Mbits/sec
[  4]   4.00-5.01   sec  13.4 MBytes   112 Mbits/sec
[  4]   5.01-6.00   sec  13.9 MBytes   117 Mbits/sec
[  4]   6.00-7.01   sec  13.0 MBytes   109 Mbits/sec
[  4]   7.01-8.01   sec  13.2 MBytes   111 Mbits/sec
[  4]   8.01-9.00   sec  13.1 MBytes   111 Mbits/sec
[  4]   9.00-10.00  sec  13.0 MBytes   109 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec   125 MBytes   105 Mbits/sec                  sender
[  4]   0.00-10.00  sec   125 MBytes   105 Mbits/sec                  receiver
```

Wireguard:
```
iperf3 -c 192.168.0.3                                      
Connecting to host 192.168.0.3, port 5201
[  4] local 192.168.233.3 port 11618 connected to 192.168.0.3 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec  5.00 MBytes  41.5 Mbits/sec
[  4]   1.01-2.01   sec  7.88 MBytes  65.8 Mbits/sec
[  4]   2.01-3.01   sec  4.88 MBytes  41.1 Mbits/sec
[  4]   3.01-4.00   sec  8.75 MBytes  73.7 Mbits/sec
[  4]   4.00-5.00   sec  6.50 MBytes  54.6 Mbits/sec
[  4]   5.00-6.00   sec  4.62 MBytes  38.7 Mbits/sec
[  4]   6.00-7.01   sec  6.00 MBytes  50.0 Mbits/sec
[  4]   7.01-8.01   sec  4.62 MBytes  39.0 Mbits/sec
[  4]   8.01-9.01   sec  5.25 MBytes  43.8 Mbits/sec
[  4]   9.01-10.01  sec  4.88 MBytes  40.8 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.01  sec  58.4 MBytes  48.9 Mbits/sec                  sender
[  4]   0.00-10.01  sec  58.2 MBytes  48.8 Mbits/sec                  receiver
```

What could be the cause? 
Wireguard is supposed to be much faster than Openvpn right?
