### ISSUE TITLE
pritunl IPv6 crash loop on iptables

### ISSUE THREAD

**Issue by MadMakz** [goofball222/pritunl#21]
Add a server, enable IPv6, click "Start Server", status changes to running, Log window remains empty.
on Console you see
```
subprocess.CalledProcessError: Command '['ip6tables', '-I', 'INPUT', '-i', 'tun23', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl-64031e51a9cfd1e2bafcc7a1']' returned non-zero exit status 3.
 ```

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:54 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:54 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
 "Id": "sha256:447fc39a4342e13ed8feb408c21a5c1976510f7db3b2c7b48c5e41a293f15caa",
        "RepoTags": [
            "goofball222/pritunl:latest"
        ],
        "RepoDigests": [
            "goofball222/pritunl@sha256:7a8293eae2bb1548caa55b934dae6afe81b43bf3a949c560e4e1290ded9d095e"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-03-01T16:14:14.112051741Z",
```
```
version: '3'

services:
  mongo:
    image: mongo:4
    container_name: pritunldb
    hostname: pritunldb
    network_mode: bridge
    volumes:
      - ./db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    depends_on:
        - mongo
    network_mode: bridge
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongo
    ports:
      - 10080:80
      - 10443:443
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
```
