### ISSUE TITLE
Container does not start when rebooting the vm

### ISSUE THREAD

**Issue by viruz82** [goofball222/pritunl#33]
## Reporting bugs/issues

* When reporting a bug/issue:
    * Ensure that you are using the latest release.
    * Revert any custom modifications or environment varibles to insure they're not the cause.

* Please provide the following information:
    * OS/distribution version (command for your OS may differ):
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

    * Docker version:
`Docker version 24.0.6, build ed223bc`

    * Labels from container:
```
    ...
                "Labels": {
                "org.opencontainers.image.created": "2023-09-22T23:16:38.353Z",
                "org.opencontainers.image.description": "Pritunl Server",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "efb0ff45e99daf934178c74af3bee1581c7a3ab5",
                "org.opencontainers.image.source": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.title": "Pritunl Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.32.3660.72"
            }
    ...
```

docker log after reboot the vm:

```
pritunl  | 2023-10-30T11:00:58.352 <docker-entrypoint> INFO - Script version 1.0.2
pritunl  | 2023-10-30T11:00:58.445 <docker-entrypoint> INFO - Insuring pritunl setup for container
pritunl  | Database configuration successfully set
pritunl  | app.web_systemd = false
pritunl  | Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
pritunl  | app.reverse_proxy = false
pritunl  | Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
pritunl  | app.redirect_server = true
pritunl  | Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
pritunl  | app.server_ssl = true
pritunl  | Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
pritunl  | app.server_port = 443
pritunl  | Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
pritunl  | 2023-10-30T11:01:54.307 <docker-entrypoint> EXEC - /usr/bin/pritunl start
pritunl  | 2023-10-30T11:06:45.969 <docker-entrypoint> INFO - Exit signal received, commencing shutdown
pritunl  | /usr/local/bin/docker-entrypoint.sh: line 56:    97 Alarm clock             exec ${PRITUNL} ${PRITUNL_OPTS}
pritunl  | 2023-10-30T11:06:49.049 <docker-entrypoint> INFO - Shutdown complete. Nothing more to see here. Have a nice day!
pritunl  | 2023-10-30T11:06:49.052 <docker-entrypoint> INFO - Exit with status code 0
```

docker-compose.yml
`
```
...
  mongo:
    image: mongo:4
    container_name: mongo
    restart: unless-stopped
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    hostname: mongo
    # network_mode: bridge
    volumes:
      - ./mongo:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    depends_on:
        mongo:
          condition: service_healthy
    # network_mode: bridge
    healthcheck:
      test: wget --no-verbose --no-check-certificate --tries=1 --spider https://localhost/login || exit 1
      interval: 10s
      retries: 10
    privileged: true
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - 80:80
      - 443:443
      # - 1194:1194
      - 1194:1194/udp
      # - 1195:1195/udp
    environment:
      - TZ=Europe/Berlin
      # - REVERSE_PROXY=true
...
```

    * Details on how to reproduce the trouble, if available:
When I restart my vm running docker pritunl always doesn't start correctly and it's always reproducable. I have to restart it every time.
