### ISSUE TITLE
Using Traefik v2 - Gateway Timeout

### ISSUE THREAD

**Issue by fniko** [goofball222/pritunl#5]
## Reporting bugs/issues

**OS/distribution version (command for your OS may differ):**

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Docker version:**

```
Docker version 19.03.5, build 633a0ea838   
```

**Labels from container:**

```bash
"Labels": {
                "org.label-schema.build-date": "2019-12-07T00:42:02Z",
                "org.label-schema.license": "Apache-2.0",
                "org.label-schema.name": "Pritunl Server",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://github.com/goofball222/pritunl",
                "org.label-schema.vcs-ref": "4d4a996",
                "org.label-schema.vcs-url": "https://github.com/goofball222/pritunl.git",
                "org.label-schema.vendor": "The Goofball - goofball222@gmail.com",
                "org.label-schema.version": "1.29.2276.91"
            }
    ...
```

**Details on how to reproduce the trouble, if available:**

I am approaching issues with running Traefik v2, I am receiving 'Gateway Timeout', my traefik config:
```
  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - private
      - proxy
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
    expose:
      - 9700
    environment:
      - TZ=UTC
      - MONGODB_URI=mongodb://mongo:27017/pritunl
      - REVERSE_PROXY=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pritunl.rule=Host(`admin.domain.com`)"
      - "traefik.http.routers.pritunl.entrypoints=web-secure"
      - "traefik.http.routers.pritunl.tls.certresolver=mytlschallenge"

```
Whole docker-compose.yml can be found here https://pastebin.com/Ymuu9HeW

Do you have any advice?

**Comment by goofball222** [comment]
I haven't messed with Traefik v2 at all, however, with that said based on a "Gateway Timeout" from Traefik and your compose file: you need to set the labels to specify the port that Traefik should proxy to (9700).

**Comment by fniko** [comment]
I adjusted the config to tell traefik explicitly to use port 9700, but with the same result (Error 502 now). I wonder whether the dashboard is even working because when I try to curl it, I receive no result at all. Is there a way how to test if the dashboard is working?

Also, could you please share example docker-compose.yml with Traefik config too? (even if it is not v2)

```
  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - private
      - proxy
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
    expose:
      - 9700
    environment:
      - TZ=UTC
      - MONGODB_URI=mongodb://mongo:27017/pritunl
      - REVERSE_PROXY=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pritunl.rule=Host(`admin.mydomain.com`)"
      - "traefik.http.routers.pritunl.entrypoints=web-secure"
      - "traefik.http.routers.pritunl.tls.certresolver=mytlschallenge"
      - "traefik.http.services.pritunl.loadbalancer.server.port=9700"
```

https://pastebin.com/xi7STHhK

![pritunl](https://user-images.githubusercontent.com/34549825/72057590-ebdcf680-32ce-11ea-8b41-9338a75463a7.png)
