### ISSUE TITLE
HTTP ERROR 502 on web interface

### ISSUE THREAD

**Issue by Kiyam** [goofball222/pritunl#8]
## Reporting bugs/issues

* When reporting a bug/issue:
    * Ensure that you are using the latest release.
    * Revert any custom modifications or environment varibles to insure they're not the cause.

* Please provide the following information:
    * OS/distribution version (command for your OS may differ):
    IE:
    ```bash
    user@host:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 18.04.4 LTS
    Release:        18.04
    Codename:       bionic
    ```

    * Docker version:
    IE:
    ```bash
    user@host:~$ docker --version
    Docker version 19.03.12, build 48a66213fe
    ```

    * Labels from container:
    IE:
    ```bash
    user@host:~$ docker inspect goofball222/pritunl:<tagname>
    ...
                "Labels": {
                "org.opencontainers.image.created": "2020-07-07T22:02:21Z",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "ac58a4a",
                "org.opencontainers.image.source": "https://github.com/goofball222/pritunl.git",
                "org.opencontainers.image.title": "Pritunl Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.29.2490.44"
            }
    ...
    ```

    * Details on how to reproduce the trouble, if available:

When trying to connect to the pritunl web interface I get a HTTP Error 502. I'm using the traefik reverse proxy config without wireguard. The config file is almost identical to the one you have stored under the example configs. Used to work fine a few months ago, and I can still connect to the set up pritunl vpn without any problems, just not the web interface.

**Comment by Kiyam** [comment]
After running docker inspect pritunl, I noticed this under the "ports" section:

```
"Ports": {                       
    "1194/tcp": [                
        {                        
            "HostIp": "0.0.0.0", 
            "HostPort": "1194"   
        }                        
    ],                           
    "1194/udp": [                
        {                        
            "HostIp": "0.0.0.0", 
            "HostPort": "1194"   
        }                        
    ],                           
    "1195/udp": null,            
    "443/tcp": null,             
    "80/tcp": null,              
    "9700/tcp": null             
},                               
```

My guess would be something is causing the 9700/tcp to return null when it probably needs something?

**Comment by goofball222** [comment]
Can you provide your sanitized run command/docker-compose.yml?

**Comment by Kiyam** [comment]
```
version: "3.6"
services:

mongo:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    restart: always
    networks:
      - default
    volumes:
      - ${USERDIR}/docker/mongo/db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    restart: always
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - default
      - traefik_proxy
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
    expose:
      - 9700
    environment:
      - TZ=${TZ}
      - MONGODB_URI=mongodb://mongo:27017/pritunl
      - REVERSE_PROXY=true
      # - WIREGUARD=false
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pritunl"
      - "traefik.frontend.rule=Host:pritunl.${DOMAINNAME}"
      - "traefik.port=9700"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```
