### ISSUE TITLE
Problems running behind traefik 2.x

### ISSUE THREAD

**Issue by ovizii** [goofball222/pritunl#9]
* Versions:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

```
docker --version
Docker version 19.03.12, build 48a66213fe
```

* Labels from container:

```
docker inspect goofball222/pritunl:latest
    ...
"Labels": {
                "org.opencontainers.image.created": "2020-07-07T22:02:21Z",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "ac58a4a",
                "org.opencontainers.image.source": "https://github.com/goofball222/pritunl.git",
                "org.opencontainers.image.title": "Pritunl Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.29.2490.44"
            }
    ...
```

* Details on how to reproduce the trouble, if available:

I have made some configuration changes to your example which I started with from here: https://github.com/goofball222/pritunl/blob/master/examples/docker-compose.traefik-reverse-proxy-wireguard.yml

Before I post all of that, maybe someone has a clue about what I did wrong as everything seems fine but visiting https://vpn.mydomain.tld gives me this error:

`Client sent an HTTP request to an HTTPS server.`

**Comment by ovizii** [comment]
traefik has this option set:

`            - "--serverstransport.insecureskipverify=true" # Allow Self Signed SSL in Backend`

here is my docker-compose.yml for pritunl + mongo

```
version: '3.7'

services:

  pritunl-mongodb:
    image: mongo:latest
    container_name: pritunl-mongodb
    hostname: pritunl-mongodb
    restart: "no"
    networks:
      - pritunl_network
    volumes:
      - /local-path/pritunl-mongodb:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    restart: "no"
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - pritunl_network
      - traefik_network
#    links:
#      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
    expose:
      - 80
      - 443
    environment:
#      - TZ=UTC
      - MONGODB_URI=mongodb://pritunl-mongodb:27017/pritunl
      - REVERSE_PROXY=true
      - WIREGUARD=true
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.pritunl.tls=true"
        - "traefik.http.routers.pritunl.entrypoints=https"
        - "traefik.http.routers.pritunl.tls.certresolver=cloudflare"
        - "traefik.http.routers.pritunl.rule=Host(`vpn.mydomain.tld`)"
        - "traefik.http.services.pritunl.loadbalancer.server.port=443"
        - "traefik.http.routers.pritunl.service=pritunl"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


networks:
  traefik_network:
    external:
      name: traefik_network
  pritunl_network:
    external:
      name: pritunl_network
```

and btw. does the pritunl container not save any data that need to be persisted or is everything saved inside the mongo db?

**Comment by ovizii** [comment]
another question is why your example here: https://github.com/goofball222/pritunl/blob/master/examples/docker-compose.traefik-reverse-proxy-wireguard.yml 

does not have the container environment variable WIREGUARD=true ?

**Comment by ovizii** [comment]
Docker logs show this error:

`2020/07/16 13:36:35 reverseproxy.go:445: httputil: ReverseProxy read error during body copy: read tcp 172.18.0.2:54042->172.18.0.8:443: read: connection reset by peer
`

pritunl:   172.18.0.8
traefik:   172.18.0.2

**Comment by goofball222** [comment]
The pritunl container doesn't have any persistent data needs, anything that should persist resides in Mongo.

Thanks for the note on the missing "WIREGUARD=true" in the example docker-compose file for reverse-proxy+wireguard. I just fixed that.

Is anything showing in the Docker logs for pritunl?

**Comment by ovizii** [comment]
Hi and thanks for the reply, I really hope you can give me a pointer, I am a bit lost figuring this out.

I added DEBUG=true and this is the log output of the pritunl container:

**docker logs -f pritunl**
```
+ log 'INFO - Script version 1.0.1'
+++ nmeter -d0 %3t
+++ head -n1
++ date -u +%FT15:49:29.276
2020-07-16T15:49:29.276 <docker-entrypoint> INFO - Script version 1.0.1
+ echo '2020-07-16T15:49:29.276 <docker-entrypoint> INFO - Script version 1.0.1'
+ PRITUNL=/usr/bin/pritunl
+ PRITUNL_OPTS=
+ trap 'kill ${!}; exit_handler' SIGHUP SIGINT SIGQUIT SIGTERM
+ [[ pritunl == \p\r\i\t\u\n\l ]]
+ pritunl_setup
+ log 'INFO - Insuring pritunl setup for container'
+++ head -n1
+++ nmeter -d0 %3t
++ date -u +%FT15:49:29.278
+ echo '2020-07-16T15:49:29.278 <docker-entrypoint> INFO - Insuring pritunl setup for container'
+ /usr/bin/pritunl set-mongodb mongodb://pritunl-mongodb:27017/pritunl
2020-07-16T15:49:29.278 <docker-entrypoint> INFO - Insuring pritunl setup for container
Database configuration successfully set
+ '[' true == true ']'
+ '[' true == false ']'
+ '[' true == true ']'
+ '[' true == true ']'
+ /usr/bin/pritunl set app.reverse_proxy true
app.reverse_proxy = true
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
+ /usr/bin/pritunl set app.redirect_server false
app.redirect_server = false
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
+ /usr/bin/pritunl set app.server_ssl true
app.server_ssl = true
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
+ /usr/bin/pritunl set app.server_port 443
app.server_port = 443
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
+ PRITUNL_OPTS='start '
+ log 'EXEC - /usr/bin/pritunl start '
+++ nmeter -d0 %3t
+++ head -n1
2020-07-16T15:49:38.561 <docker-entrypoint> EXEC - /usr/bin/pritunl start
++ date -u +%FT15:49:38.561
+ echo '2020-07-16T15:49:38.561 <docker-entrypoint> EXEC - /usr/bin/pritunl start '
+ exec
+ idle_handler
+ true
+ wait 53
+ exec /usr/bin/pritunl start
+ tail -f /dev/null
##############################################################

```
while the traefik container only shows:

`2020/07/17 07:05:47 reverseproxy.go:445: httputil: ReverseProxy read error during body copy: read tcp 172.18.0.2:39956->172.18.0.8:443: read: connection reset by peer
`

I don'T have debugging enabled yet for traefik, do you have any clue why it is saying 

`Client sent an HTTP request to an HTTPS server.`

YES; traefik redirects http to https but I am accessing my web interface using https so all should be good or is the pritunl interface somehow reverting to http, then traefik reverts it to https?

I am a bit lost, I use traefik in front of many services but usually the service "backend" itself does not run on https as traefik handles that beeing the reverse proxy.

**Comment by ovizii** [comment]
Any ideas? Does anyone see any problems with the adapted docker-compose.yml I posted above? 

I tried checking the connection from inside the traefik and pritunl container:

```
docker exec -ti pritunl bash
wget --no-check-certificate https://pritunl:443
wget: server returned error: HTTP/1.1 502 Bad Gateway

```

from inside the traefik container:

```
docker exec -ti traefik sh
wget --no-check-certificate https://pritunl:443
Connecting to pritunl:443 (172.18.0.8:443)
wget: server returned error: HTTP/1.1 502 Bad Gateway

```

The problem seems to stem from pritunl itself:
`server returned error: HTTP/1.1 502 Bad Gateway`

###edit###
I haven't configured wireguard, simply installed it on the host - am I missing a step here?

**Comment by ovizii** [comment]
I just thought to check the pritunl logs inside the container but they are not helpful at all:


`docker exec -ti pritunl bash`
```
bash-5.0# cat /var/log/pritunl.log
[undefined][2020-07-23 09:29:54,416][INFO] Starting setup server
[undefined][2020-07-23 09:29:54,419][INFO] Generating setup server ssl cert
[autumn-waterfall-6328][2020-07-23 09:29:57,686][INFO] Starting server
  selinux_context = "none"
[autumn-waterfall-6328][2020-07-23 09:29:57,688][INFO] Generating server certificate...

```

**Comment by ovizii** [comment]
I removed the volume that held the persistent data of mondodb and tried your docker-compose file WITH reverse proxy but without Wireguard and am running into the exact same problem :-(

**Comment by ovizii** [comment]
is there an overview what options this variable can take? => PRITUNL_OPTS 
I still can't get this to work so I thought I'd look into these possible options.

**Comment by ovizii** [comment]
I am still struggling to get this working so I now checked with your original docker-compose.yml file => 

and after starting it if I enter the pritunl container I still get a "bad gateway" error, could someone please double check if they are not getting this error?

```
/opt/pritunl # wget --no-check-certificate https://localhost
Connecting to localhost (127.0.0.1:443)
wget: server returned error: HTTP/1.1 502 Bad Gateway

```

while netstat show the port is listening:

```
/opt/pritunl # netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:35539        0.0.0.0:*               LISTEN      -
tcp        0      0 :::443                  :::*                    LISTEN      117/pritunl-web
tcp        0      0 ::1:9756                :::*                    LISTEN      51/python2
udp        0      0 127.0.0.11:43822        0.0.0.0:*                           -

```

**Comment by jpmeijers** [comment]
I am getting the same error. Not running behind Traefik, but I did map port 443 in the container to port 1443 of the host.

**Comment by pingod** [comment]
this is my docker-compose ,it works ok.

```
version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: pritunldb
    hostname: pritunldb
#    networks:
#      - private
#    volumes:
#      - ./db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
#    networks:
#      - private
#      - proxy
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
    expose:
      - 443
    environment:
      - TZ=UTC
      - MONGODB_URI=mongodb://mongo:27017/pritunl
      - REVERSE_PROXY=true
      - WIREGUARD=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.pritunl.service=pritunl
      - traefik.http.services.pritunl.loadbalancer.server.port=443
      - traefik.http.services.pritunl.loadbalancer.server.scheme=https
      - traefik.http.routers.pritunl.rule=Host(`admin.mydomain.com`)
      - traefik.http.routers.pritunl.tls=true
      - "traefik.http.routers.pritunl.entrypoints=web-secure"
      - "traefik.http.routers.pritunl.tls.certresolver=mytlschallenge"


  traefik:
    image: "traefik:v2.3"
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--serverstransport.insecureskipverify=true"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=info@mydomain.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    labels:
      #Traefik dashboard config
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.admin.mydomain.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web-secure"
      - "traefik.http.routers.traefik.tls.certresolver=mytlschallenge"
 
      #Middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
 
      #global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=https-redirect"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

#networks:
#  proxy:
#    external:
#      name: proxy
#  private:
#    driver: bridge
#    internal: true
```
